### ISSUE TITLE
analysis differs from SAPWIN and seems wrong

### ISSUE THREAD

**Issue by llemtt** [skypjack/qsapecng#1]
[circuit.sch.txt](https://github.com/skypjack/qsapecng/files/761085/circuit.sch.txt)
[circuit.info.txt](https://github.com/skypjack/qsapecng/files/761086/circuit.info.txt)
Hi,

I came across a circuit (see attached schematics) that results in a different output under SAPWIN (both v3 and v4), the SAPWIN analysis seems the correct one and simulates like LTSPICE.

SAPWIN:

(  +1871.5) s

(  +4.005) s^2

(  -0.495) s^3

------------------------------------------------------------------------------

(  +10000)

(  +11928.5) s

(  +61.995) s^2

(  +0.495) s^3

qsapecng:

( - 1 ) * s^3 + 8.09091 * s^2 + 23982.8 * s + 20202
----------------------------------------------------------------------------
1 * s^3 + 125.242 * s^2 + 24098 * s + 20202

**Comment by skypjack** [comment]
Unfortunately QSapecNG is no longer supported, mainly because I've no more free time to work on it.
I would be glad if someone decides to contribute and solve these issues and I'm willing to help to transfer the knowledge to work on it.
If you are interested, feel free to let me know and we can arrange a chat.

**Comment by skypjack** [comment]
Well, I suspect you aren't interested in contributing to the project. Thank you anyway for pointing out the error.
